resources:
    - name: code
      type: git
      source: {uri: 'https://github.com/schehata/garson'}

jobs:
    - name: test
      plan:
        - get: code
          trigger: true
        - task: test
          file: code/ci/tasks/test.yml
